---
- hosts: server
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Create default containers
      docker_container:
         name: "{{ default_container_name }}{{ item }}"
         image: "{{ default_container_image }}"
         state: present
      with_sequence: count={{ create_containers }}
    
